default_permissions = "project-edit"

[permissions.project-edit]
extends = ":workspace"

[permissions.project-edit.workspace_roots]
"C:\\Users\\Johannes Milos\\.gradle" = true

[permissions.project-edit.network]
enabled = true

[permissions.project-edit.network.domains]
"localhost" = "allow"
"127.0.0.1" = "allow"