plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	maven {
		name = "ParchmentMC"
		url = 'https://maven.parchmentmc.org'
	}

	maven { url = "https://api.modrinth.com/maven" }
	maven { url = "https://mvn.devos.one/releases/" }

	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/"
	}

	maven {
		name = 'Xander Maven'
		url = 'https://maven.isxander.dev/releases'
	}
}

loom {
	splitEnvironmentSourceSets()

	loom {
		runs {
			datagen {
				server()
				name "Data Generation"
				vmArg "-Dfabric-api.datagen"
				vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
				vmArg "-Dfabric-api.datagen.modid=substance"
			}
		}
	}

	mods {
		"substance" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

fabricApi {
	/*
	configureDataGeneration {
		client = true
	}
	*/
}

sourceSets {
	main {
		resources {
			srcDirs += "src/main/generated"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${rootProject.minecraft_version}:2023.09.03@zip")
	}
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Create
	modImplementation("maven.modrinth:create-fabric:${project.create_fabric_version}")
	modImplementation(include("io.github.fabricators_of_create.Porting-Lib:fluids:2.3.15+1.20.1"))

	// Config (ModMenu + YACL)
	modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
	modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"

	testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.10.2"
}

tasks.named("test") {
	useJUnitPlatform()
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
