package jojoaky.substance.datagen;

import net.fabricmc.fabric.api.datagen.v1.DataGeneratorEntrypoint;
import net.fabricmc.fabric.api.datagen.v1.FabricDataGenerator;

public class DataGen implements DataGeneratorEntrypoint {

    @Override
    public void onInitializeDataGenerator(FabricDataGenerator fabricDataGenerator) {
        final FabricDataGenerator.Pack pack = fabricDataGenerator.createPack();
        pack.addProvider(ChemicalModelProvider::new);

        // Seems like this is automatically generated by create if the item is a fluid storage
        //pack.addProvider(SubstanceRecipeProvider::registerAllProcessing);
    }
}